import 'package:drift/drift.dart';

/// Documents table - main storage for document metadata
class Documents extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(min: 1, max: 255)();
  TextColumn get category => text()();
  TextColumn get filePath => text()(); // encrypted file location
  TextColumn get thumbnailPath => text().nullable()();
  IntColumn get fileSizeBytes => integer()();
  TextColumn get mimeType => text()();
  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get modifiedAt => dateTime()();
  TextColumn get tags => text().withDefault(const Constant('[]'))();
  BoolColumn get isFavorite => boolean().withDefault(const Constant(false))();
  TextColumn get extractedText => text().nullable()(); // OCR result
  BoolColumn get isOcrProcessed => boolean().withDefault(const Constant(false))();
  TextColumn get cloudStorageUrl => text().nullable()();
  BoolColumn get isSynced => boolean().withDefault(const Constant(false))();
  DateTimeColumn get lastSyncedAt => dateTime().nullable()();
}

/// Extracted data from documents (intelligent analysis)
class ExtractedData extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get documentId => integer().references(Documents, #id, onDelete: KeyAction.cascade)();
  TextColumn get dataType => text()(); // 'expiration_date', 'document_number', 'issue_date'
  TextColumn get value => text()();
  DateTimeColumn get dateValue => dateTime().nullable()();
  RealColumn get confidence => real().withDefault(const Constant(0.0))();
  DateTimeColumn get extractedAt => dateTime()();
}

/// Reminders for documents
class Reminders extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get documentId => integer().references(Documents, #id, onDelete: KeyAction.cascade)();
  TextColumn get title => text()();
  TextColumn get description => text().nullable()();
  DateTimeColumn get reminderDate => dateTime()();
  BoolColumn get isAutoGenerated => boolean().withDefault(const Constant(false))();
  BoolColumn get isCompleted => boolean().withDefault(const Constant(false))();
  IntColumn get notificationId => integer().nullable()();
  DateTimeColumn get createdAt => dateTime()();
}

/// User notes for documents
class UserNotes extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get documentId => integer().references(Documents, #id, onDelete: KeyAction.cascade)();
  TextColumn get content => text()();
  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();
}

/// Document categories
class Categories extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text().unique()();
  TextColumn get icon => text()(); // emoji or icon code
  IntColumn get sortOrder => integer()();
  BoolColumn get isSystem => boolean().withDefault(const Constant(false))();
  DateTimeColumn get createdAt => dateTime()();
}

/// Full-text search virtual table
@DataClassName('DocumentFts')
class DocumentsFts extends Table {
  IntColumn get rowid => integer()();
  TextColumn get title => text()();
  TextColumn get extractedText => text()();
  TextColumn get tags => text()();
}

